
package br.cnpq.repositorio.servico.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSCurriculo", targetNamespace = "http://ws.servico.repositorio.cnpq.br/", wsdlLocation = "file:/D:/Projetos/FAPEPI/br.gov.pi.fapepi.extrator/src/main/resources/WSCurriculo.wsdl")
public class WSCurriculo_Service
    extends Service
{

    private final static URL WSCURRICULO_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.cnpq.repositorio.servico.ws.WSCurriculo_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.cnpq.repositorio.servico.ws.WSCurriculo_Service.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/Projetos/FAPEPI/br.gov.pi.fapepi.extrator/src/main/resources/WSCurriculo.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/Projetos/FAPEPI/br.gov.pi.fapepi.extrator/src/main/resources/WSCurriculo.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSCURRICULO_WSDL_LOCATION = url;
    }

    public WSCurriculo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCurriculo_Service() {
        super(WSCURRICULO_WSDL_LOCATION, new QName("http://ws.servico.repositorio.cnpq.br/", "WSCurriculo"));
    }

    /**
     * 
     * @return
     *     returns WSCurriculo
     */
    @WebEndpoint(name = "WSCurriculoPort")
    public WSCurriculo getWSCurriculoPort() {
        return super.getPort(new QName("http://ws.servico.repositorio.cnpq.br/", "WSCurriculoPort"), WSCurriculo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCurriculo
     */
    @WebEndpoint(name = "WSCurriculoPort")
    public WSCurriculo getWSCurriculoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.servico.repositorio.cnpq.br/", "WSCurriculoPort"), WSCurriculo.class, features);
    }

}
